Aquarela Virtual/V0/socioenactivevirtuality-main/admin/views.py
from oficina import Oficina
from flask import Blueprint, url_for, render_template, request, redirect, session, make_response
oficina = Oficina.getInstance()
from foto_captura import Foto
from uteis.funcoes import resolve_id
#Configuração Blueprint
bp_admin= Blueprint('admin',__name__,static_folder='static',template_folder='templates')
foto = Foto.getInstance()
#Rotas Blueprint (Módulo admin)
@bp_admin.route('/index', methods=['GET',])
@bp_admin.route('/', methods=['GET',])
def login():
    return render_template('login.html',titulo_pagina='Administração')

@bp_admin.route('/validarfoto', methods=['GET','POST'])
def validar_foto():
    if request.method == "POST":
        print("No post...")
        if 'senha' in request.form:
            print("Senha no forms...")
            if request.form['senha'] == 'interhad':
                print("Validou Senha...")
                resp = make_response(render_template('validar_fotos.html',titulo_pagina='Validar fotos', lista_fotos = foto.listar_arquivos_fotos()))  
                resp.set_cookie('admin',"00000") 
                return resp
            else:
                return render_template('login.html',titulo_pagina='Administração')
    else:
        if 'admin' in request.cookies:
            return render_template('validar_fotos.html', titulo_pagina='Validar fotos', lista_fotos = foto.listar_arquivos_fotos())
        else:
            return render_template('login.html',titulo_pagina='Administração')

Aquarela Virtual/V0/socioenactivevirtuality-main/admin/templates/login.html
{% extends "template_modulo_admin.html" %}
{% block conteudo_dinamico %}
	<div class="conteudo_login">
		<h1 style="margin-top: -222px" id="logo"><strong><span id="letra-1">A</span><span id="letra-2">q</span><span id="letra-3">u</span><span id="letra-4">a</span><span id="letra-5">r</span><span id="letra-6">e</span><span id="letra-7">l</span><span id="letra-8">a</span> <span id="palavra-virtual">Virtual</span></strong></h1>
        <h1 id="titulo">Painel de Adiminstração</h1>
        <form id="login" name="login" method="POST" action="{{ url_for('admin.validar_foto') }}">
            <input name="senha" id="senha" type="password" maxlength="30" placeholder="Digite sua senha"/>
            <button id="bntFazerLogin" type="submit" alt="Login"> <i class="fas fa-key fa-1x"></i> <strong>Login</strong> </button>
    	</form>
    </div>
{% endblock %}

Aquarela Virtual/V0/socioenactivevirtuality-main/admin/templates/validar_fotos.html
{% extends "template_modulo_admin.html" %}
{% block conteudo_dinamico %}
<aside>
    <div class="cabecalho">
        <div id="logo-oficina">
            <h1 style="padding-left: 15px; font-size: 1.5em;" id="logo"> 
                <strong>
                        <span id="letra-1">A</span>
                        <span id="letra-2">q</span>
                        <span id="letra-3">u</span>
                        <span id="letra-4">a</span>
                        <span id="letra-5">r</span>
                        <span id="letra-6">e</span>
                        <span id="letra-7">l</span>
                        <span id="letra-8">a</span>
                        <span id="palavra-virtual">Virtual</span>
                        <span id="painel-adm"> - Painel de Administração</span>
                </strong>
            </h1>
            <sapn id="lastAction"></sapn>
        </div>

        <div id="oficina">
            <div>
                <h3> <i class="fa fa-desktop" aria-hidden="true"></i><strong>  Oficina: </strong></h3>
            </div>
            <div>
                <h3 id="nome-oficina"></h3>
            </div>
        </div>
        
    </div>
</aside>
<main>
    <div id="myModal" class="modal">
        <div class="modal-content">
          <span class="close">&times;</span>
          <p id="acao-modal">?</p>
          <button class="btnModal" id="btnModalCancel">Cancelar</button>
          <button class="btnModal" id="btnModalConfirm">Confirmar</button>
        </div>    
    </div>

    <div class="main-painel">
        <div class="menu-lateral">
            <div id="controle">
                <p id="secao-menu-lateral"> <i class="fa fa-cogs" aria-hidden="true"></i> <strong>Controle Oficina</strong></p>
                <button type="button" class="btnControle" id="btnTerminar" onclick="modalAcao({evento: this.value, acao: this.id})" name="btnTO" value="ENCERRAR A OFICINA">Encerrar Oficina</button>
                <button type="button" class="btnControle" id="btnEstrofe" onclick="modalAcao({evento: this.value, acao: this.id})" name="btnEE" value="TERMINAR A ESTROFE">Terminar Estrofe</button>
                <div id='excluir-fotos'>
                    <div id="selecao-fotos">
                        <div>
                            <h4> <strong>Fotos selecionadas:</strong></h4>
                        </div>
                        <div>
                            <h4 style="margin-left: 0.5em;" id="fotos-selecionadas">0</h4>
                        </div>
                    </div>
                    <button style ="width: 92%;" class="btnControle" id="btnExcluirSelecao" onclick="modalAcao({evento: this.value, acao: this.id})" type="button" value="EXCLUIR A(s) FOTO(s)" alt="Excluir Seleção"> Excluir Fotos </button> 
                    <div id="fotos-excluidas">
                        <div>
                            <h4> <strong>Fotos excluídas:</strong></h4>
                        </div>
                        <div>
                            <h4 style="margin-left: 0.5em;" id="fotos-movidas">0</h4>
                        </div>
                    </div>
                </div> 
                <div id='renomear-oficina'>
                    <input style="margin-top: 1em;" type="text" required value="" id="novo-nome-oficina" name="novo_nome" placeholder="">
                    <button style ="width: 92%; margin-top: 1em;" type="button" class="btnControle" id="btnRenomearOficina" onclick="modalAcao({evento: document.getElementById('novo-nome-oficina').value, acao: this.id})" name="btnTO" >Renomear Oficina</button>
                </div>   
                <div id='gerar-zip'>
                    <button style ="width: 92%; margin-top: 1em;" type="button" class="btnControle" id="btnGerarZip" onclick="gerarZip()" name="btnZip" >Gerar Dados</button>
                    <br><span id="link-download"></span>
                </div> 
            </div>

            <hr>

            <div class="participantes-online" id="participante-online">
                <p id="secao-menu-lateral"> <i class="fa fa-users" aria-hidden="true"></i> <strong>Participantes Online</strong><p>         
            </div>
        </div>

        <div class="gerenciamento-fotos">
            <div id="painel-fotos">
                    <h2>  <i class="far fa-images"></i>  Gerenciamento Fotos</h2>
                    <div id="infos-fotos">
                        <div>
                            <h4> <strong>Quantidade fotos:</strong></h4>
                        </div>
                        <div>
                            <h4 style="margin-left: 0.5em;" id="qtde-fotos"></h4>
                        </div>
                        <div style="margin-left: 2em;">
                            <h4> <strong>Tempo estimado por foto:</strong></h4>
                        </div>
                        <div>
                            <h4 style="margin-left: 0.5em;" id="tempo-fotos"></h4>
                        </div> 
                    </div>     
            </div>

            <div id="fotos" name="fotos">
                <ul id="lista-fotos">
                    {% for item in lista_fotos|reverse: %}
                    {% if lista_fotos|length == 0 %}
                        <h2>Não há fotos disponíveis para avaliar.</h2>
                    {% else %}
                    <li id="id{{item['caminho']}}">
                        <input onchange="verficarMudanca(this)" type="checkbox" id="{{item['caminho']}}" />
                        <label class="label_foto" for="{{item['caminho']}}">
                            <img src="{{url_for('static',filename=item['caminho'])}}" />
                            <div>
                                {{item['descricao']}}
                            </div>
                        </label>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</main>
{% endblock %}

Aquarela Virtual/V0/socioenactivevirtuality-main/templates/folha_desenho.html
{% set pagina = 'desenho' %}
{% extends "template_master.html" %}
{% block conteudo_dinamico %}
<header class="animate__animated animate__fadeInUp">
    <h1 ><span id="letra-1">A</span><span id="letra-2">q</span><span id="letra-3">u</span><span id="letra-4">a</span><span id="letra-5">r</span><span id="letra-6">e</span><span id="letra-7">l</span><span id="letra-8">a</span> <span id="palavra-virtual">Virtual</span></h1>

    <div id="perfil-participante">
        <p>
          <img src="{{ url_avatar }}" alt="tigre" /> {{ nome_participante }} <a class="editar" title="Mudar nome e figura" href="{{url_for('index')}}"><i class="far fa-edit"></i></a>
        </p>
    </div>
</header>
<main>
    <div class="animate__animated animate__rotateInUpLeft">
    <section id="folha-papel">
        <!--elementos_estrofe_1-->
        <div id="estrofe1" class="estrofe escondido">
          <div id="sol">
            <img src="{{url_for('static',filename='images/designs/sol.svg')}}" id="sol-img" alt="sol-img" >
          </div>
          <div id="castelo">
            <img src="{{url_for('static',filename='images/designs/castelo.svg')}}" id="castelo-img" alt="castelo-img" >
          </div>
          <div id="campo">
            <img src="{{url_for('static',filename='images/designs/campo.svg')}}" id="campo-img" alt="campo-img" >
          </div>
          <div id="estrofe1-avatares"></div>
        </div>
        <!--elementos_estrofe_2-->
        <div id="estrofe2" class="estrofe escondido">
          <div id="mundo" class="mundo" >
            <img src="{{url_for('static',filename='images/designs/mundo.svg')}}" id="mundo-img" alt="mundo-img" >
          </div>
          <div id="pingo-tinta" class="pingo-tinta" >
            <img src="{{url_for('static',filename='images/designs/pingo.svg')}}" id="pingo-tinta-img" alt="pingo-tinta-img" >
          </div>
          <div id="splash-tinta" class="escondido" >
            <img src="{{url_for('static',filename='images/designs/splash.png')}}" id="splash-img" alt="splash-img" >
          </div>
          <div id="container-gaivota">
            <svg viewBox="0 0 800 800">
              <path id="caminho-gaivota" fill="transparent" stroke="#888888" stroke-width="0" d="M 0 250 Q 100 150 200 200 Q 300 250 400 250 Q 500 250 600 200 Q 700 150 800 250 "></path>
            </svg>
            <div id="gaivota">
              <img src="{{url_for('static',filename='images/designs/gaivota1.svg')}}" id="gaivota-img" alt="gaivota-img" >
            </div>
          </div>
          <div id="estrofe2-avatares"></div>
        </div>
        <!--elementos_estrofe_3-->
        <div id="estrofe3" class="estrofe escondido">
            <div class="oceano">
                  <div class="mySlides ondas-mar fade">
                    <img src="{{url_for('static',filename='images/designs/oceano1.svg')}}" style="width:100%">
                  </div>
                  <div class="mySlides ondas-mar fade">
                    <img src="{{url_for('static',filename='images/designs/oceano2.svg')}}" style="width:100%">
                  </div>
                  <div class="mySlides ondas-mar fade">
                    <img src="{{url_for('static',filename='images/designs/oceano3.svg')}}" style="width:100%">
                  </div>
            </div>
            <div style="text-align:center">
              <span class="dot"></span>
              <span class="dot"></span>
              <span class="dot"></span>
            </div>
            <div id="estrofe3-avatares"></div>
            <div id="estrofe3-background-avatares"></div>
            <div id="barco-a-vela" class="barco-a-vela">
              <img src="{{url_for('static',filename='images/designs/barco.svg')}}" id="barco-a-vela-img" alt="barco-a-vela-img" >
            </div>
        </div>
        <!--elementos_estrofe_4-->
        <div id="estrofe4" class="estrofe escondido">
          <div id="nuvem1">
            <img src="{{url_for('static',filename='images/designs/nuvem1.svg')}}" style="width:100%">
          </div>
          <div id="nuvem2">
            <img src="{{url_for('static',filename='images/designs/nuvem2.svg')}}" style="width:100%">
          </div>
          <div id="nuvem3">
            <img src="{{url_for('static',filename='images/designs/nuvem1.svg')}}" style="width:100%">
          </div>
          <div id="nuvem4">
            <img src="{{url_for('static',filename='images/designs/nuvem2.svg')}}" style="width:100%">
          </div>

          <div id=estrela1> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela2> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela3> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela4> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela5> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela6> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>
          <div id=estrela7> <img src="{{url_for('static',filename='images/designs/star.png')}}" style="width:100%"> </div>

          <div id="aviao" class="aviao">
            <img src="{{url_for('static',filename='images/designs/aviao.svg')}}" id="aviao-img" alt="aviao-img" >
          </div>
          <div id="nuvem5">
            <img src="{{url_for('static',filename='images/designs/nuvem2.svg')}}" style="width:100%">
          </div>

          <div id="estrofe4-avatares"></div>
        </div>
        <!--elementos_grand_finale-->
        <div id="grand_finale" class="estrofe escondido">
          <div id="grand_finale_avatares"></div>
          <div id="grand_finale_stickers">
            <img src="{{url_for('static',filename='images/designs/mundo_sticker.svg')}}" id="mundo_sticker" 
              style="width: 155px; position: absolute; left: 5%; bottom: 230%; z-index: 10;">
            <img src="{{url_for('static',filename='images/designs/aviao_sticker.svg')}}" id="aviao_sticker"
              style="width: 270px; position: absolute; left:6%; bottom:89%; z-index: 10;">
            <img src="{{url_for('static',filename='images/designs/gaivota_sticker.svg')}}" id="gaivota_sticker"
              style="width:140px; left:80%; position: absolute; bottom:180%; transform:rotate(341deg); z-index:10;">
            <img src="{{url_for('static',filename='images/designs/castelo_sticker.svg')}}" id="castelo_sticker"
            style="width:240px; position:relative; left:79%; bottom:50px; transform: rotate(348deg); z-index: 10;">
          </div>
        </div>

    </section>
    </div>

    <aside class="animate__animated animate__fadeInRight">
        <h2>Criando junto</h2>
        <ul id="lista_participantes"></ul>

        <div id="camera">
            <button id="tirar-foto" type="button" alt="Tirar foto" class="escondido"> <i class="fas fa-camera fa-1x"></i> <strong>Tirar foto</strong> </button>
            <span class="fa-stack fa-4x escondido" id="erro-webcam">
                  <p>Erro ao inicializar a câmera.</p>
                  <i class="fas fa-camera fa-stack-1x"></i>
                  <i class="fas fa-ban fa-stack-2x"></i>
            </span>
            <div id="minha-camera"></div>
        </div>
    </aside>
</main>
{% endblock %}

Aquarela Virtual/V0/socioenactivevirtuality-main/templates/login_participante.html
{% set pagina = 'login' %}
{% extends "template_master.html" %}
{% block conteudo_dinamico %}

<div class="conteudo_login">
	<section id="folha-papel">
		<h1><span id="letra-1">A</span><span id="letra-2">q</span><span id="letra-3">u</span><span id="letra-4">a</span><span id="letra-5">r</span><span id="letra-6">e</span><span id="letra-7">l</span><span id="letra-8">a</span> <span id="palavra-virtual">Virtual</span></h1>

    <form id="frm_login_participante" name="frm_login_participante" action="{{url_for('quadro_desenho')}}" method="POST">
        <label for="nome" id="labelNome"><strong>Nome</strong></label>
        <input name="nome" id="nome" type="text" value="{{ nome_participante }}" maxlength="20" minlength="3" placeholder="" autofocus required/>

        <label for="avatar" id="labelAvatar"><strong>Avatar</strong></label>
        <label>
			<input type="radio" id="hipopotamo" name="avatar" value="hipopotamo" required />
			<img src="{{url_for('static',filename='images/avatar/hipoppotamus_emoji.png')}}" alt="hipopotamo" title="hipopotamo" aria-label="hipopotamo">
		</label>
		<label>
			<input type="radio" id="gato" name="avatar" value="gato" required />
			<img src="{{url_for('static',filename='images/avatar/cat_emoji.png')}}" alt="gato" title="gato" />
		</label>
		<label>
			<input type="radio" id="panda" name="avatar" value="panda" required />
			<img src="{{url_for('static',filename='images/avatar/panda_emoji.png')}}" alt="panda" title="panda" />
		</label>
		<label>
			<input type="radio" id="guaxinim" name="avatar" value="guaxinim" required />
			<img src="{{url_for('static',filename='images/avatar/raccoon_emoji.png')}}" alt="guaxinim" title="guaxinim" required />
		</label>
		<label>
			<input type="radio" id="macaco" name="avatar" value="macaco" required />
			<img src="{{url_for('static',filename='images/avatar/monkey_emoji.png')}}" alt="macaco" title="macaco" />
		</label>
		<label>
			<input type="radio" id="tigre" name="avatar" value="tigre" required />
			<img src="{{url_for('static',filename='images/avatar/tiger_emoji.png')}}" alt="tigre" title="tigre" />
		</label>
		<label>
			<input type="radio" id="coala" name="avatar" value="coala" required />
			<img src="{{url_for('static',filename='images/avatar/koala_emoji.png')}}" alt="coala" title="coala" />
		</label>
		<label>
			<input type="radio" id="gorila" name="avatar" value="gorila" required />
			<img src="{{url_for('static',filename='images/avatar/gorilla_emoji.png')}}" alt="gorila" title="gorila" />
		</label>
		<br>
		<label>
			<input type="radio" id="coelho" name="avatar" value="coelho" required />
			<img src="{{url_for('static',filename='images/avatar/rabbit_emoji.png')}}" alt="coelho" title="coelho" />
		</label>
		<label>
			<input type="radio" id="raposa" name="avatar" value="raposa" required />
			<img src="{{url_for('static',filename='images/avatar/fox_emoji.png')}}" alt="raposa" title="raposa" />
		</label>
		<label>
			<input type="radio" id="vaca" name="avatar" value="vaca" required />
			<img src="{{url_for('static',filename='images/avatar/cow_emoji.png')}}" alt="vaca" title="vaca" />
		</label>
		<label>
			<input type="radio" id="urso" name="avatar" value="urso" required />
			<img src="{{url_for('static',filename='images/avatar/bear_emoji.png')}}" alt="urso" title="urso" />
		</label>
		<label>
			<input type="radio" id="cachorro" name="avatar" value="cachorro" required />
			<img src="{{url_for('static',filename='images/avatar/dog_emoji.png')}}" alt="cachorro" title="cachorro" />
		</label>
		<label>
			<input type="radio" id="porco" name="avatar" value="porco" required />
			<img src="{{url_for('static',filename='images/avatar/pig_emoji.png')}}" alt="porco" title="porco" />
		</label>
		<label>
			<input type="radio" id="leao" name="avatar" value="leao" required />
			<img src="{{url_for('static',filename='images/avatar/lion_emoji.png')}}" alt="leão" title="leão" />
		</label>
		<label>
			<input type="radio" id="lobo" name="avatar" value="lobo" required />
			<img src="{{url_for('static',filename='images/avatar/wolf_emoji.png')}}" alt="lobo" title="lobo" />
		</label>
		<br>

		<button id="bntFazerLogin" type="submit" alt="Participar da Aquarela"> <i class="fas fa-door fa-1x"></i> <img src="{{url_for('static',filename='images/login/airplane.png')}}" required /> </button>
    </form>
	</section>

	
	<script type="text/javascript">
			function check_avatar(){
				if ('{{avatar}}' != ''){
					document.getElementById('{{avatar}}').checked = true;
					document.getElementById("nome").focus();
				}
			}
			check_avatar();

	</script>
</div>
{% endblock %}

Aquarela Virtual/V0/socioenactivevirtuality-main/templates/template_master.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/normalize-8.0.1.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/animate-4.1.1.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/fontawesome.all.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos_' ~ pagina ~ '.css') }}">
        <style>
            .tooltip {
                font: 1.2rem sans-serif;
                background-color: #333333;
                color: #EEEEEE;
                padding: 0.5em;
                border-radius: 0.5em;
            }
        </style>
        <title>{{ titulo_pagina }}</title>
    </head>

    <body>
        {% block conteudo_dinamico %}
        {% endblock %}
    </body>

    <script src="{{ url_for('static', filename='js/lib/socket.io-4.2.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/webcam-1.0.25.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/qrcode-decoder-0.2.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/anime-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/lib/itooltip-1.1.1.js') }}"></script>
    <script>
        var tooltip = new iTooltip();
        tooltip.init();
    </script>
    <script src="{{ url_for('static', filename='js/script_' ~ pagina ~ '.js') }}"></script>
</html>

Aquarela Virtual/V0/socioenactivevirtuality-main/templates/template_modulo_admin.html
<!DOCTYPE html>
<html lang="pt-br">

    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/fontawesome.all.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos_validar_fotos.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos_login_admin.css') }}">
        <title>{{ titulo_pagina }}</title>
    </head>
    
    <body>
        
            {% block conteudo_dinamico %}
            {% endblock %}
    </body>

     <script src="{{ url_for('static', filename='js/lib/socket.io-4.2.0.min.js') }}"></script>
     <script src="{{ url_for('static', filename='js/script_admin.js') }}"></script>

</html>